# Generated by Django 4.2.4 on 2023-08-17 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('air_date', models.DateField()),
                ('episode', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=150)),
                ('dimension', models.CharField(max_length=150)),
                ('url', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('image', models.TextField()),
                ('url', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('episode', models.ManyToManyField(related_name='Episodes', to='app.episode')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='app.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origin', to='app.location')),
            ],
        ),
    ]
